version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "simple-sam-demo"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-blhggg4obcrr"
s3_prefix = "simple-sam-demo"
region = "sa-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
