---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  simple_sam_demo

  Sample SAM Template for simple_sam_demo

Globals:
  Function:
    Runtime: python3.8
    Handler: app.lambda_handler
    Timeout: 3

Resources:
  WriteIrisFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/write_iris/
      Events:
        WriteIris:
          Type: Api
          Properties:
            Path: /v0/iris
            Method: POST
      Policies:
        DynamoDBCrudPolicy:
          TableName: iris_table

  ReadIrisFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/read_iris/
      Events:
        WriteIris:
          Type: Api
          Properties:
            Path: /v0/iris/{id}
            Method: GET

  IrisTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: iris_table

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
