AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  simple_sam_demo

  Sample SAM Template for simple_sam_demo

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: python3.8
    Handler: app.lambda_handler
    Timeout: 3

Resources:
  WriteIrisFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/write_iris/
      Events:
        WriteIris:
          Type: Api 
          Properties:
            Path: /v0/iris
            Method: POST

  ReadIrisFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/read_iris/
      Events:
        WriteIris:
          Type: Api 
          Properties:
            Path: /v0/iris/{id}
            Method: GET

  IrisTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: iris_table

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  # HelloWorldFunction:
  #   Description: "Hello World Lambda Function ARN"
  #   Value: !GetAtt HelloWorldFunction.Arn
  # HelloWorldFunctionIamRole:
  #   Description: "Implicit IAM Role created for Hello World function"
  #   Value: !GetAtt HelloWorldFunctionRole.Arn
