---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  simple_sam_demo

  Sample SAM Template for simple_sam_demo

Globals:
  Function:
    Runtime: python3.8
    Handler: app.lambda_handler
    Timeout: 3

Resources:
  WriteIrisFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/write_iris/
      Events:
        WriteIris:
          Type: Api
          Properties:
            Path: /v0/iris
            Method: POST
      Policies:
        DynamoDBCrudPolicy:
          TableName: iris_table
      Layers:
        - !Ref InternalLayer

  ProcessIrisDynamoDBStream:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/process_iris_stream/
      Policies:
        DynamoDBCrudPolicy:
          TableName: iris_table
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt IrisTable.StreamArn
            BatchSize: 5
            StartingPosition: TRIM_HORIZON
      Layers:
        - !Ref SklearnLayer
        - !Ref InternalLayer

  IrisTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: iris_table
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  InternalLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: ./internal_layer
      CompatibleRuntimes:
        - python3.8
    Metadata:
      BuildMethod: makefile

  SklearnLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: SklearnLayer
      ContentUri: ./sklearn_layer
      CompatibleRuntimes:
        - python3.8
    Metadata:
      BuildMethod: python3.8


Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
